### ISSUE TITLE
debian 9.8 make error

### ISSUE THREAD

**Issue by heysion** [sanpii/effitask#35]
## On the Debian 9.8 make error ?

1. git clone source
2. sudo apt install libgtk-3-dev
3. make 

## What happens?

```
 make
cargo build  --release
warning: unused manifest key: package.edition
   Compiling autocfg v0.1.2
   Compiling rand_core v0.4.0
   Compiling serde v1.0.89
   Compiling fragile v0.3.0
error: use of unstable library feature 'thread_local_state': state querying was recently added (see issue #27716)
   --> /home/xx/.cargo/registry/src/github.com-1ecc6299db9ec823/fragile-0.3.0/src/sticky.rs:100:27
    |
100 |         unsafe { REGISTRY.try_with(|registry| (*registry.get()).0.contains_key(&self.item_id)).unwrap_or(false) }
    |                           ^^^^^^^^

error: aborting due to previous error

error: Could not compile `fragile`.
warning: build failed, waiting for other jobs to finish...
error: build failed
Makefile:15: recipe for target 'build' failed
make: *** [build] Error 101

```
rustc 1.24.1+dfsg1-1~deb9u4

**Comment by heysion** [comment]
@sanpii  Would you show me you Cargo.lock file  that we need known the depends version~

**Comment by sixstarkalu** [comment]
@sanpii ,
I'm having errors (11 of them) like heysion after make.
I'm running on xubuntu 18.04 and rustc 1.35.0-nightly (cb2f34dc6 2019-03-22)

btw, thanks for creating this plugin. look forward to using it.

what I did:
0. terminal
1. git clone source
2. sudo apt install libgtk-3-dev
3. curl https://sh.rustup.rs -sSf | sh
4. rebooted and logged back in
5. cd effitask
6. make

recv'd these errors:
$ make
cargo build  --release
   Compiling effitask v0.1.0 (/home/john/nextcloud_local/programs/0_cross_platform/effitask)
error: expected `,`
   --> src/application/widget.rs:448:74
    |
448 |                           TagsWidget(crate::widgets::tags::Type::Projects) {
    |  __________________________________________________________________________^
449 | |                             TagsComplete(ref task) => Msg::Complete(task.clone()),
450 | |                             TagsEdit(ref task) => Msg::Edit(task.clone()),
451 | |                         },
    | |_________________________^

error: expected `,`
   --> src/edit.rs:199:60
    |
199 |                           Calendar("Defer until".to_owned()) {
    |  ____________________________________________________________^
200 | |                             CalendarUpdated(date) => Msg::UpdateDate(DateType::Threshold, date),
201 | |                         },
    | |_________________________^

error: expected `,`
   --> src/widgets/task.rs:221:49
    |
221 |                   Circle(self.model.task.clone()) {
    |  _________________________________________________^
222 | |                     child: {
223 | |                         expand: false,
224 | |                         fill: true,
225 | |                     },
226 | |                 },
    | |_________________^

error[E0432]: unresolved import `crate::edit::Widget`
  --> src/application/widget.rs:12:5
   |
12 | use crate::edit::Widget as EditWidget;
   |     ^^^^^^^^^^^^^------^^^^^^^^^^^^^^
   |     |            |
   |     |            help: a similar name exists in the module: `widget`
   |     no `Widget` in `edit`

error[E0432]: unresolved import `self::widget::Widget`
 --> src/application/mod.rs:9:9
  |
9 | pub use self::widget::Widget;
  |         ^^^^^^^^^^^^^^------
  |         |             |
  |         |             help: a similar name exists in the module: `widget`
  |         no `Widget` in `application::widget`

error[E0432]: unresolved import `self::task::Task`
  --> src/widgets/mod.rs:18:9
   |
18 | pub use self::task::Task;
   |         ^^^^^^^^^^^^^^^^ no `Task` in `widgets::task`

error[E0412]: cannot find type `Widget` in this scope
  --> src/application/widget.rs:60:24
   |
60 |     relm: ::relm::Relm<Widget>,
   |                        ^^^^^^ not found in this scope
help: possible candidates are found in other modules, you can import them into scope
   |
1  | use crate::add::Widget;
   |
1  | use crate::agenda::Widget;
   |
1  | use crate::done::Widget;
   |
1  | use crate::flag::Widget;
   |
and 5 other candidates

error[E0412]: cannot find type `Widget` in this scope
  --> src/application/widget.rs:84:6
   |
84 | impl Widget {
   |      ^^^^^^ not found in this scope
help: possible candidates are found in other modules, you can import them into scope
   |
1  | use crate::add::Widget;
   |
1  | use crate::agenda::Widget;
   |
1  | use crate::done::Widget;
   |
1  | use crate::flag::Widget;
   |
and 5 other candidates

error[E0412]: cannot find type `Widget` in this scope
  --> src/edit.rs:25:24
   |
25 |     relm: ::relm::Relm<Widget>,
   |                        ^^^^^^ not found in this scope
help: possible candidates are found in other modules, you can import them into scope
   |
1  | use crate::add::Widget;
   |
1  | use crate::agenda::Widget;
   |
1  | use crate::done::Widget;
   |
1  | use crate::flag::Widget;
   |
and 5 other candidates

error[E0412]: cannot find type `Widget` in this scope
  --> src/edit.rs:35:6
   |
35 | impl Widget {
   |      ^^^^^^ not found in this scope
help: possible candidates are found in other modules, you can import them into scope
   |
1  | use crate::add::Widget;
   |
1  | use crate::agenda::Widget;
   |
1  | use crate::done::Widget;
   |
1  | use crate::flag::Widget;
   |
and 5 other candidates

error[E0412]: cannot find type `Task` in this scope
  --> src/widgets/task.rs:19:24
   |
19 |     relm: ::relm::Relm<Task>,
   |                        ^^^^ not found in this scope
help: possible candidates are found in other modules, you can import them into scope
   |
1  | use crate::tasks::task::Task;
   |
1  | use todo_txt::Task;
   |
1  | use todo_txt::task::Task;
   |

warning: unused import: `relm::Widget`
  --> src/main.rs:10:5
   |
10 | use relm::Widget;
   |     ^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

warning: unused import: `crate::agenda::Msg::Complete as AgendaComplete`
 --> src/application/widget.rs:5:5
  |
5 | use crate::agenda::Msg::Complete as AgendaComplete;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::agenda::Msg::Edit as AgendaEdit`
 --> src/application/widget.rs:6:5
  |
6 | use crate::agenda::Msg::Edit as AgendaEdit;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::agenda::Widget as AgendaWidget`
 --> src/application/widget.rs:7:5
  |
7 | use crate::agenda::Widget as AgendaWidget;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::done::Msg::Complete as DoneComplete`
 --> src/application/widget.rs:8:5
  |
8 | use crate::done::Msg::Complete as DoneComplete;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::done::Msg::Edit as DoneEdit`
 --> src/application/widget.rs:9:5
  |
9 | use crate::done::Msg::Edit as DoneEdit;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::done::Widget as DoneWidget`
  --> src/application/widget.rs:10:5
   |
10 | use crate::done::Widget as DoneWidget;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused imports: `Cancel`, `Done`
  --> src/application/widget.rs:11:24
   |
11 | use crate::edit::Msg::{Cancel, Done};
   |                        ^^^^^^  ^^^^

warning: unused import: `crate::edit::Widget as EditWidget`
  --> src/application/widget.rs:12:5
   |
12 | use crate::edit::Widget as EditWidget;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::flag::Msg::Complete as FlagComplete`
  --> src/application/widget.rs:13:5
   |
13 | use crate::flag::Msg::Complete as FlagComplete;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::flag::Msg::Edit as FlagEdit`
  --> src/application/widget.rs:14:5
   |
14 | use crate::flag::Msg::Edit as FlagEdit;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::flag::Widget as FlagWidget`
  --> src/application/widget.rs:15:5
   |
15 | use crate::flag::Widget as FlagWidget;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::inbox::Msg::Complete as InboxComplete`
  --> src/application/widget.rs:16:5
   |
16 | use crate::inbox::Msg::Complete as InboxComplete;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::inbox::Msg::Edit as InboxEdit`
  --> src/application/widget.rs:17:5
   |
17 | use crate::inbox::Msg::Edit as InboxEdit;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::inbox::Widget as InboxWidget`
  --> src/application/widget.rs:18:5
   |
18 | use crate::inbox::Widget as InboxWidget;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::logger::Widget as LoggerWidget`
  --> src/application/widget.rs:19:5
   |
19 | use crate::logger::Widget as LoggerWidget;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::search::Msg::Complete as SearchComplete`
  --> src/application/widget.rs:20:5
   |
20 | use crate::search::Msg::Complete as SearchComplete;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::search::Msg::Edit as SearchEdit`
  --> src/application/widget.rs:21:5
   |
21 | use crate::search::Msg::Edit as SearchEdit;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::search::Widget as SearchWidget`
  --> src/application/widget.rs:22:5
   |
22 | use crate::search::Widget as SearchWidget;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::widgets::tags::Msg::Complete as TagsComplete`
  --> src/application/widget.rs:23:5
   |
23 | use crate::widgets::tags::Msg::Complete as TagsComplete;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::widgets::tags::Msg::Edit as TagsEdit`
  --> src/application/widget.rs:24:5
   |
24 | use crate::widgets::tags::Msg::Edit as TagsEdit;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::widgets::Tags as TagsWidget`
  --> src/application/widget.rs:25:5
   |
25 | use crate::widgets::Tags as TagsWidget;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::widgets::calendar::Msg::Updated as CalendarUpdated`
 --> src/edit.rs:4:5
  |
4 | use crate::widgets::calendar::Msg::Updated as CalendarUpdated;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::widgets::keywords::Msg::Updated as KeywordsUpdated`
 --> src/edit.rs:5:5
  |
5 | use crate::widgets::keywords::Msg::Updated as KeywordsUpdated;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::widgets::priority::Msg::Updated as PriorityUpdated`
 --> src/edit.rs:6:5
  |
6 | use crate::widgets::priority::Msg::Updated as PriorityUpdated;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::widgets::repeat::Msg::Updated as RepeatUpdated`
 --> src/edit.rs:7:5
  |
7 | use crate::widgets::repeat::Msg::Updated as RepeatUpdated;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused imports: `Calendar`, `Keywords`, `Priority`, `Repeat`
 --> src/edit.rs:8:22
  |
8 | use crate::widgets::{Calendar, Keywords, Priority, Repeat};
  |                      ^^^^^^^^  ^^^^^^^^  ^^^^^^^^  ^^^^^^

warning: unused import: `gtk::prelude::*`
 --> src/widgets/task.rs:2:5
  |
2 | use gtk::prelude::*;
  |     ^^^^^^^^^^^^^^^

warning: unused import: `crate::widgets::Circle`
 --> src/widgets/task.rs:4:5
  |
4 | use crate::widgets::Circle;
  |     ^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `relm::ContainerWidget`
   --> src/application/widget.rs:132:13
    |
132 |         use relm::ContainerWidget;
    |             ^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `relm::Widget`
   --> src/application/widget.rs:270:13
    |
270 |         use relm::Widget;
    |             ^^^^^^^^^^^^

warning: unused import: `gtk::prelude`
 --> src/edit.rs:2:5
  |
2 | use gtk::prelude::*;
  |     ^^^^^^^^^^^^

error: aborting due to 11 previous errors

Some errors occurred: E0412, E0432.
For more information about an error, try `rustc --explain E0412`.
error: Could not compile `effitask`.

To learn more, run the command again with --verbose.
Makefile:15: recipe for target 'build' failed
make: *** [build] Error 101

**Comment by sanpii** [comment]
https://github.com/antoyo/relm/issues/162

**Comment by sixstarkalu** [comment]
@sanpii thank you for the reply. I looked through the issues earlier. I didn't think to look for unable to compile widget though. appreciate the share. I'll attempt to compile a later version or wait for updated version.

**Comment by sanpii** [comment]
@sixstarkalu the compilation error is fixed :smiley:

**Comment by sixstarkalu** [comment]
@sanpii thank you. appreciate it.

**Comment by sanpii** [comment]
This issue is old, I assume it’s fixed. Fell free to reopen it if it’s not the case.
